- name: variable playbook 
  hosts: localhost
   vars_file: varfile.yml
   vars:
       URL: "www.com.com"
    tasks:
      - name: one 
       debug:
         msg: "{{ URL}}"

      - name: two
       debug:
         msg: "{{ URL}}"
       vars:
         URL: "AWS.CERTIFICATEWALE.COM"  
